version: "3.8"

services:
  prometheus:
    container_name: ccp-prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    container_name: ccp-grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    extra_hosts:
      - "host.docker.internal:host-gateway"
  app:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: ccp-api-server
    ports:
      - "8082:8082"
    restart: on-failure
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  grafana-storage: { }