global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "CCP_APP"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [ "host.docker.internal:8082" ]
